#!/usr/bin/env python3
"""Generate complete ModVeins.java: merged veins + indicators."""
from pathlib import Path

p = Path('src/main/java/com/mss/polymech/worldgen/ModVeins.java')
shape_map = {}

def add_def(vid, rarity, minY, maxY, mult, density, primary, secondary, between, sporadic,
        rocks, shape=None, indicator=None):
    if shape:
        shape_map[vid] = shape
    btw = f'"{between}"' if between else 'null'
    spo = f'"{sporadic}"' if sporadic else 'null'
    ind = indicator or 'VeinIndicator.none()'
    return (f'            // {vid}\n'
            f'            new VeinDefinition(\n'
            f'                    "{vid}", {rarity}, {minY}, {maxY}, {mult}F, {density}F,\n'
            f'                    "{primary}", "{secondary}", {btw}, {spo},\n'
            f'                    {rocks}, {ind})')

defs = []
S = add_def  # shorthand

defs.append(S("cassiterite", 2, 80, 300, 0.85, 0.4, "cassiterite", "cassiterite", None, "tin", 'Set.of("diorite", "gabbro", "granite")', "PIPE", 'VeinIndicator.surface("cassiterite", 12)'))
defs.append(S("gabbro_garnierite", 20, -64, 16, 1.3, 0.6, "garnierite", "garnierite", None, None, 'Set.of("gabbro")', None, 'VeinIndicator.deep("garnierite", 7)'))
defs.append(S("garnierite", 25, -48, 24, 0.85, 0.3, "garnierite", "garnierite", None, "cobalt", 'Set.of("diorite", "gabbro", "granite")', None, 'VeinIndicator.underground("garnierite", 5)'))
defs.append(S("native_silver", 15, -40, 280, 1.15, 0.4, "native_silver", "native_silver", None, "silver", 'Set.of("diorite", "gneiss", "granite", "schist")', "PIPE", 'VeinIndicator.underground("native_silver", 9)'))
defs.append(S("bismuthinite", 40, -48, 220, 1.15, 0.4, "bismuthinite", "bismuthinite", None, None, 'Set.of("chalk", "chert", "claystone", "conglomerate", "diorite", "dolomite", "gabbro", "granite", "limestone", "shale", "tuff")', None, 'VeinIndicator.underground("bismuthinite", 4)'))
defs.append(S("sphalerite", 40, -48, 220, 1.15, 0.4, "sphalerite", "sphalerite", None, None, 'Set.of("andesite", "basalt", "dacite", "diorite", "gabbro", "granite", "rhyolite")', None, 'VeinIndicator.underground("sphalerite", 5)'))
defs.append(S("tetrahedrite", 30, -30, 270, 1.15, 0.4, "tetrahedrite", "tetrahedrite", None, None, 'METAMORPHIC6', None, 'VeinIndicator.underground("tetrahedrite", 4)'))
defs.append(S("malachite", 35, -30, 100, 1.15, 0.4, "malachite", "malachite", None, None, 'Set.of("chalk", "dolomite", "limestone", "marble")', None, 'VeinIndicator.underground("malachite", 4)'))
defs.append(S("native_copper", 20, 40, 300, 0.85, 0.25, "native_copper", "native_copper", None, None, 'IGNEOUS4', None, 'VeinIndicator.surface("native_copper", 14)'))
defs.append(S("native_gold", 90, 0, 70, 0.85, 0.25, "native_gold", "native_gold", None, "gold", 'IGNEOUS7', None, 'VeinIndicator.underground("native_gold", 3)'))
defs.append(S("rich_native_gold", 50, -48, 24, 1.4, 0.5, "native_gold", "native_gold", None, None, 'Set.of("diorite", "gabbro", "granite")', None, 'VeinIndicator.deep("native_gold", 4)'))
defs.append(S("hematite", 35, 10, 250, 0.85, 0.4, "hematite", "hematite", None, None, 'IGNEOUS4', None, 'VeinIndicator.surface("hematite", 24)'))
defs.append(S("magnetite", 50, 10, 250, 0.85, 0.4, "magnetite", "magnetite", None, None, 'SED8', None, 'VeinIndicator.surface("magnetite", 24)'))
defs.append(S("limonite", 50, 10, 250, 0.85, 0.4, "limonite", "limonite", None, None, 'SED8', None, 'VeinIndicator.surface("limonite", 24)'))
defs.append(S("copper_porphyry", 30, -24, 48, 1.4, 0.35, "chalcopyrite", "bornite", "chalcocite", "copper", 'Set.of("diorite", "granite", "andesite", "dacite")', "DISSEMINATED", 'VeinIndicator.underground("chalcopyrite", 4)'))
defs.append(S("galena", 45, -16, 48, 1.3, 0.5, "galena", "galena", "native_silver", "lead", 'Set.of("limestone", "dolomite", "shale")', None, 'VeinIndicator.underground("galena", 4)'))
defs.append(S("bauxite", 40, 0, 80, 1.6, 0.5, "bauxite", "bauxite", None, "aluminium", 'Set.of("limestone", "claystone", "shale")', None, 'VeinIndicator.underground("bauxite", 4)'))
defs.append(S("nickel_sulfide", 40, 0, 70, 1.15, 0.25, "garnierite", "pentlandite", "cobaltite", "nickel", 'Set.of("gabbro", "basalt")', None, 'VeinIndicator.underground("garnierite", 4)'))
defs.append(S("chromite", 30, -48, -8, 1.3, 0.4, "chromite", "ilmenite", "magnetite", "iron", 'Set.of("gabbro", "basalt")', None, 'VeinIndicator.deep("chromite", 6)'))
defs.append(S("pgm", 40, -48, -10, 1.15, 0.25, "cooperite", "platinum", "palladium", "bornite", 'Set.of("gabbro", "basalt")', None, 'VeinIndicator.deep("cooperite", 6)'))
defs.append(S("molybdenum", 20, -16, 32, 1.15, 0.25, "molybdenite", "wulfenite", "powellite", "molybdenum", 'Set.of("granite", "rhyolite")', "DISSEMINATED", 'VeinIndicator.underground("molybdenite", 5)'))
defs.append(S("wolframite", 60, -40, 16, 1.15, 0.35, "wolframite", "scheelite", None, "tungstate", 'Set.of("granite", "gneiss")', None, 'VeinIndicator.underground("wolframite", 4)'))
defs.append(S("manganese", 20, -32, 24, 1.3, 0.45, "grossular", "spessartine", "pyrolusite", "tantalite", 'Set.of("schist", "quartzite", "gneiss")', None, 'VeinIndicator.underground("grossular", 5)'))
defs.append(S("stibnite", 40, -16, 32, 1.15, 0.3, "stibnite", "stibnite", None, "native_gold", 'Set.of("granite", "gneiss", "quartzite")', None, 'VeinIndicator.underground("stibnite", 4)'))
defs.append(S("rare_earth", 40, -32, 16, 1.15, 0.25, "bastnasite", "monazite", None, "neodymium", 'Set.of("granite", "gneiss")', None, 'VeinIndicator.underground("bastnasite", 5)'))
defs.append(S("uranium", 40, -48, -8, 1.15, 0.3, "pitchblende", "uraninite", None, "plutonium_239", 'Set.of("granite", "gneiss", "schist")', "DISSEMINATED", 'VeinIndicator.deep("pitchblende", 6)'))
defs.append(S("beryllium", 30, -24, 32, 0.85, 0.3, "beryllium", "thorium", None, "emerald", 'Set.of("granite", "rhyolite")', None, 'VeinIndicator.underground("beryllium", 5)'))
defs.append(S("graphite", 20, -30, 60, 1.15, 0.4, "graphite", "graphite", None, None, 'Set.of("gneiss", "marble", "quartzite", "schist")', None, 'VeinIndicator.underground("graphite", 5)'))
defs.append(S("cinnabar", 14, -48, 280, 0.85, 0.6, "cinnabar", "cinnabar", None, None, 'Set.of("gneiss", "phyllite", "quartzite", "schist")', None, 'VeinIndicator.surface("cinnabar", 14)'))
defs.append(S("sulfur_deep", 4, -56, -40, 0.85, 0.25, "sulfur", "sulfur", None, None, 'Set.of("diorite", "gabbro", "gneiss", "granite", "marble", "phyllite", "quartzite", "schist", "slate")', "LAYER", 'VeinIndicator.deep("sulfur", 6)'))
defs.append(S("tuff_sulfur", 2, 40, 200, 0.85, 0.45, "sulfur", "sulfur", None, None, 'Set.of("tuff")', None, 'VeinIndicator.surface("sulfur", 12)'))
defs.append(S("gypsum", 70, 40, 100, 1.0, 0.3, "gypsum", "gypsum", None, None, 'SED8', "LAYER", 'VeinIndicator.surface("gypsum", 14)'))
defs.append(S("borax", 40, 40, 100, 1.0, 0.2, "borax", "borax", None, None, 'Set.of("claystone", "limestone", "shale")', "LAYER", 'VeinIndicator.surface("borax", 14)'))
defs.append(S("cryolite", 16, -48, 0, 0.85, 0.7, "cryolite", "cryolite", None, None, 'Set.of("diorite", "granite")', None, 'VeinIndicator.deep("cryolite", 6)'))
defs.append(S("saltpeter", 110, 40, 100, 1.15, 0.4, "saltpeter", "saltpeter", None, None, 'SED8', "LAYER", 'VeinIndicator.surface("saltpeter", 14)'))
defs.append(S("sylvite", 60, 40, 100, 1.15, 0.35, "sylvite", "sylvite", None, "trona", 'Set.of("chert", "claystone", "shale")', "LAYER", 'VeinIndicator.surface("sylvite", 14)'))
defs.append(S("bituminous_coal", 210, 0, 40, 1.4, 0.9, "bituminous_coal", "bituminous_coal", None, None, 'SED8', "LAYER", 'VeinIndicator.surface("bituminous_coal", 14)'))
defs.append(S("lignite", 160, 10, 50, 1.15, 0.85, "lignite", "lignite", None, None, 'SED8', "LAYER", 'VeinIndicator.surface("lignite", 14)'))
defs.append(S("lapis_lazuli", 30, -20, 80, 1.3, 0.12, "lapis_lazuli", "lazurite", "sodalite", "calcite", 'Set.of("limestone", "marble")', None, 'VeinIndicator.underground("lapis_lazuli", 5)'))
defs.append(S("amethyst", 25, 40, 60, 0.7, 0.2, "amethyst", "amethyst", None, None, 'Set.of("chalk", "chert", "claystone", "conglomerate", "dolomite", "gneiss", "limestone", "marble", "phyllite", "quartzite", "schist", "shale", "slate", "tuff")', "LAYER", 'VeinIndicator.surface("amethyst", 14)'))
defs.append(S("opal", 25, 40, 60, 0.7, 0.2, "opal", "opal", None, None, 'Set.of("andesite", "basalt", "chalk", "chert", "claystone", "conglomerate", "dacite", "dolomite", "limestone", "rhyolite", "shale", "tuff")', "LAYER", 'VeinIndicator.surface("opal", 14)'))
defs.append(S("diamond", 30, -64, 100, 0.7, 0.15, "diamond", "diamond", None, "olivine", 'Set.of("gabbro")', "PIPE", 'VeinIndicator.deep("diamond", 4)'))
defs.append(S("emerald", 80, -64, 100, 0.7, 0.15, "emerald", "emerald", None, None, 'Set.of("diorite", "gabbro", "granite")', "PIPE", 'VeinIndicator.deep("emerald", 5)'))
defs.append(S("deep_ruby", 80, -48, -8, 1.15, 0.2, "ruby", "ruby", None, None, 'Set.of("marble")', None, 'VeinIndicator.deep("ruby", 5)'))
defs.append(S("ruby_marble_belt", 16, -32, 4, 1.4, 0.45, "ruby", "ruby", "calcite", None, 'Set.of("andesite", "basalt", "dacite", "diorite", "gabbro", "gneiss", "granite", "marble", "phyllite", "quartzite", "rhyolite", "schist", "slate")', "LAYER", 'VeinIndicator.underground("ruby", 5)'))
defs.append(S("pyrite", 16, -50, 70, 0.85, 0.35, "pyrite", "pyrite", None, None, 'IGNEOUS7', None, 'VeinIndicator.underground("pyrite", 5)'))
defs.append(S("sapphire", 60, -32, 16, 1.15, 0.25, "almandine", "sapphire", "pyrope", "green_sapphire", 'Set.of("gneiss", "schist", "phyllite", "marble")', None, 'VeinIndicator.underground("sapphire", 5)'))
defs.append(S("garnet_dike", 40, -10, 50, 1.3, 0.45, "red_garnet", "yellow_garnet", "andradite", "opal", 'Set.of("schist", "gneiss", "marble")', "DIKE", 'VeinIndicator.underground("red_garnet", 4)'))
defs.append(S("topaz_greisen", 60, -16, 32, 0.85, 0.25, "topaz", "blue_topaz", None, "quartzite", 'Set.of("granite", "rhyolite", "dacite")', None, 'VeinIndicator.underground("topaz", 5)'))
defs.append(S("apatite", 40, 10, 80, 1.15, 0.25, "apatite", "tricalcium_phosphate", None, "pyrochlore", 'Set.of("limestone", "marble", "claystone")', None, 'VeinIndicator.underground("apatite", 4)'))
defs.append(S("salts", 50, 30, 70, 1.3, 0.2, "rock_salt", "salt", "spodumene", "lepidolite", 'Set.of("shale", "claystone", "limestone", "chalk")', None, 'VeinIndicator.underground("rock_salt", 4)'))
defs.append(S("mica", 20, -24, 16, 1.15, 0.25, "kyanite", "mica", "bauxite", "pollucite", 'Set.of("gneiss", "schist", "phyllite", "quartzite")', None, 'VeinIndicator.underground("kyanite", 5)'))
defs.append(S("mineral_sand", 80, 15, 60, 1.4, 0.2, "basaltic_mineral_sand", "granitic_mineral_sand", "fullers_earth", "gypsum", 'Set.of("conglomerate", "shale", "claystone", "chalk")', None, 'VeinIndicator.surface("basaltic_mineral_sand", 20)'))
defs.append(S("placer", 80, 30, 60, 1.3, 0.4, "cassiterite_sand", "garnet_sand", "asbestos", "diatomite", 'Set.of("conglomerate", "chert", "claystone")', None, 'VeinIndicator.surface("cassiterite_sand", 20)'))
defs.append(S("oilsands", 40, 30, 80, 1.3, 0.3, "oilsands", "oilsands", None, None, 'Set.of("conglomerate", "shale", "claystone")', None, 'VeinIndicator.surface("oilsands", 20)'))
defs.append(S("redstone", 60, -48, 0, 1.3, 0.2, "redstone", "redstone", None, "cinnabar", 'Set.of("schist", "gneiss", "phyllite", "slate")', None, 'VeinIndicator.deep("redstone", 5)'))
defs.append(S("olivine", 20, -8, 32, 1.15, 0.25, "olivine", "magnesite", "bentonite", "glauconite_sand", 'Set.of("basalt", "gabbro")', None, 'VeinIndicator.underground("olivine", 5)'))
defs.append(S("talc_zeolite", 25, -16, 32, 1.15, 0.3, "talc", "zeolite", "calcite", "magnesite", 'Set.of("marble", "schist", "phyllite", "dolomite", "basalt", "andesite")', None, 'VeinIndicator.underground("talc", 4)'))
defs.append(S("alunite", 40, 0, 64, 0.85, 0.25, "alunite", "alunite", None, None, 'Set.of("rhyolite", "dacite")', None, 'VeinIndicator.underground("alunite", 4)'))
defs.append(S("realgar", 30, -32, 32, 0.85, 0.3, "realgar", "realgar", "sulfur", None, 'Set.of("rhyolite", "dacite", "andesite")', None, 'VeinIndicator.underground("realgar", 4)'))
defs.append(S("barite", 40, -16, 40, 1.15, 0.25, "barite", "barite", "calcite", "galena", 'Set.of("limestone", "dolomite", "shale")', None, 'VeinIndicator.underground("barite", 4)'))
defs.append(S("goethite", 60, 0, 64, 0.7, 0.3, "goethite", "goethite", None, "vanadium_magnetite", 'SED8', None, 'VeinIndicator.underground("goethite", 4)'))
defs.append(S("banded_iron", 40, -32, 24, 1.3, 0.4, "vanadium_magnetite", "magnetite", "iron", "iron", 'Set.of("gneiss", "quartzite", "schist")', None, 'VeinIndicator.deep("vanadium_magnetite", 5)'))

shape_entries = [f'            Map.entry("{k}", VeinShape.{shape_map[k]})' for k in sorted(shape_map)]

out = []
out.append('package com.mss.polymech.worldgen;')
out.append('')
out.append('import java.util.List;')
out.append('import java.util.Map;')
out.append('import java.util.Set;')
out.append('')
out.append('import javax.annotation.Nullable;')
out.append('')
out.append('public final class ModVeins {')
out.append('')
out.append('    public record VeinIndicator(int surfaceRarity, int depth, int undergroundRarity, int undergroundCount, String mineral) {')
out.append('        public static VeinIndicator surface(String m, int r) { return new VeinIndicator(r, 35, 1, 0, m); }')
out.append('        public static VeinIndicator deep(String m, int c) { return new VeinIndicator(0, 35, 1, c, m); }')
out.append('        public static VeinIndicator underground(String m, int c) { return new VeinIndicator(0, 35, 1, c, m); }')
out.append('        public static VeinIndicator none() { return new VeinIndicator(0, 0, 1, 0, ""); }')
out.append('    }')
out.append('')
out.append('    public record VeinDefinition(')
out.append('            String id, int rarity, int minY, int maxY, int sizeMin, int sizeMax,')
out.append('            float density, String primary, String secondary,')
out.append('            @Nullable String between, @Nullable String sporadic,')
out.append('            Set<String> allowedRocks, VeinIndicator indicator) {')
out.append('        public VeinDefinition(String id, int rarity, int minY, int maxY, int size,')
out.append('                float density, String p, String s, @Nullable String b, @Nullable String sp, Set<String> r) {')
out.append('            this(id, rarity, minY, maxY, size, size, density, p, s, b, sp, r, VeinIndicator.none()); }')
out.append('        public VeinDefinition(String id, int rarity, int minY, int maxY, float mul,')
out.append('                float density, String p, String s, @Nullable String b, @Nullable String sp, Set<String> r) {')
out.append('            this(id, rarity, minY, maxY, Math.max(2, Math.round(BASE_SIZE_MIN * mul)),')
out.append('                    Math.max(2, Math.round(BASE_SIZE_MAX * mul)), density, p, s, b, sp, r, VeinIndicator.none()); }')
out.append('        public VeinDefinition(String id, int rarity, int minY, int maxY, float mul,')
out.append('                float density, String p, String s, @Nullable String b, @Nullable String sp, Set<String> r, VeinIndicator i) {')
out.append('            this(id, rarity, minY, maxY, Math.max(2, Math.round(BASE_SIZE_MIN * mul)),')
out.append('                    Math.max(2, Math.round(BASE_SIZE_MAX * mul)), density, p, s, b, sp, r, i); }')
out.append('        public int size() { return (sizeMin + sizeMax) / 2; }')
out.append('    }')
out.append('')
out.append('    public static final int BASE_SIZE_MIN = 5;')
out.append('    public static final int BASE_SIZE_MAX = 9;')
out.append('')
out.append('    public enum VeinShape { ELLIPSOID, LAYER, PIPE, DIKE, DISSEMINATED }')
out.append('')
out.append('    private static final Map<String, VeinShape> VEIN_SHAPES = Map.ofEntries(')
out.append(',\n'.join(shape_entries))
out.append('    );')
out.append('')
out.append('    public static VeinShape shapeOf(String id) { return VEIN_SHAPES.getOrDefault(id, VeinShape.ELLIPSOID); }')
out.append('')
out.append('    private static final Set<String> SED8 = Set.of("limestone", "shale", "chalk", "chert", "claystone", "conglomerate", "dolomite", "tuff");')
out.append('    private static final Set<String> IGNEOUS4 = Set.of("andesite", "basalt", "dacite", "rhyolite");')
out.append('    private static final Set<String> IGNEOUS7 = Set.of("andesite", "basalt", "dacite", "diorite", "gabbro", "granite", "rhyolite");')
out.append('    private static final Set<String> METAMORPHIC6 = Set.of("gneiss", "marble", "phyllite", "quartzite", "schist", "slate");')
out.append('')
out.append('    public static final List<VeinDefinition> DEFINITIONS = List.of(')
out.append(',\n'.join(defs))
out.append('    );')
out.append('')
out.append('    private ModVeins() {}')
out.append('    public static List<VeinDefinition> getDefinitions() { return DEFINITIONS; }')
out.append('}')

p.write_text('\n'.join(out), encoding='utf-8')
print(f'Written ModVeins.java: {len(defs)} veins, {len(shape_map)} shapes')
